### ISSUE TITLE
Use Dockerfile from cloud-builders-community ?

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-bootstrap#24]
What are your thoughts on using the `cloud-builders-community` [Dockerfile](https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/terraform/Dockerfile) which seems a bit simpler ? This would avoid code duplication and make it easier to keep it up-to-date (PR to `cloud-builders-community` repo).

If I understand this [docs](https://github.com/docker/docker.github.io/blob/master/develop/develop-images/dockerfile_best-practices.md#build-from-a-remote-build-context-using-a-dockerfile-from-stdin) correctly, we could use `docker build https://github.com/cloud-builders-community.git#master:terraform --tag gcr.io/$PROJECT_ID/terraform` to build from GitHub.

Example `cloudbuild.yaml`:

```
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - build
    - https://github.com/cloud-builders-community#master:terraform
    --tag
    - gcr.io/${PROJECT_ID}/terraform
- name: 'gcr.io/${PROJECT_ID}/terraform'
  args: ['version']
images: ['gcr.io/${PROJECT_ID}/terraform']
```
